use azumi::prelude::*;

#[azumi::component]
pub fn ClassSyntaxVerification() -> impl Component {
    html! {
        <style>
            .snake_class { color: "blue"; }
            .other_class { font-weight: "bold"; }
        </style>

        // 1. Variable Usage (Standard)
        // snake_class variable is auto-generated by macro
        <div class={snake_class}>"Variable"</div>

        // 2. Static String (Auto-scoped)
        <div class="snake_class">"Static"</div>

        // 3. Expression List (Combine variables)
        <div class={ snake_class other_class }>"Check List"</div>
    }
}
